#release configuration
#Sun Mar 23 00:54:31 IST 2025
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.form.login\:ApplicationSecureGateWay=1.0.1-SNAPSHOT
project.rel.com.form.login\:ApplicationSecureGateWay=1.0.0
project.scm.com.form.login\:ApplicationSecureGateWay.connection=scm\:git\:https\://github.com/subhojitbasak/ApplicationSecureGateWay.git
project.scm.com.form.login\:ApplicationSecureGateWay.developerConnection=scm\:git\:https\://github.com/subhojitbasak/ApplicationSecureGateWay.git
project.scm.com.form.login\:ApplicationSecureGateWay.tag=v1.0.0
project.scm.com.form.login\:ApplicationSecureGateWay.url=https\://github.com/subhojitbasak/ApplicationSecureGateWay
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v1.0.0
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:https\://github.com/subhojitbasak/ApplicationSecureGateWay.git
